#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl3,  led,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           raiseOne,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightWheel,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           leftWheel,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           grabber,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           raiseTwo,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           liftOne,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           liftTwo,       tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
	motor[rightWheel] = 127;
	motor[leftWheel] = 127;
	delay(1000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//Move with Buttons
void buttonControls(){
  	if(vexRT[Btn8U]==0&&vexRT[Btn8D]==0)
		{
			motor[rightWheel]  = 0;
			motor[rightWheel]  = 0;
		}
		else if(vexRT[Btn8U]==1){
			motor[rightWheel] = 127;
			motor[leftWheel] = 127;
		}
		else if(vexRT[Btn8D]==1){
			motor[rightWheel] = -127;
			motor[leftWheel] = -127;
		}
		else if(vexRT[Btn8R]==1){
			motor[rightWheel] = 127;
			motor[leftWheel] = -127;
		}
		else if(vexRT[Btn8L]==1){
			motor[rightWheel] = -127;
			motor[leftWheel] = 127;
		}
}

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	//move with buttons
  	buttonControls();
		//Move with joysticks
		motor[rightWheel] = vexRT[Ch2] - vexRT[Ch1];
		motor[leftWheel] = vexRT[Ch2] + vexRT[Ch1];

		//raise and lower lift
		motor[raiseOne] = vexRT[Ch3];
		motor[raiseTwo] = vexRT[Ch3];

		//raise and lift x-lift in unison
		if(vexRT[Btn7U]==1){
			motor[liftOne] = 127;
			motor[liftTwo] = 127;
		}
		else if(vexRT[Btn7D]==1){
			motor[liftOne] = -127;
			motor[liftTwo] = -127;
		}

		//one side x-lift at a time
		else if(vexRT[Btn8L]==1){
			motor[liftOne] = 127;
		}
		else if(vexRT[Btn8R]==1){
			motor[liftTwo] = 127;
		}
		else{
			motor[liftOne] = 0;
			motor[liftTwo] = 0;
		}

		//Grab with x-lift rubbers
		if(vexRT[Btn7L]==1){
			motor[grabber] = 127;
		}
		else if(vexRT[Btn7R]==1){
			motor[grabber] = -127;
		}else{
			motor[grabber] = 0;
		}
  }
}
