#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl3,  led,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           grabber,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightWheel,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           rightWheelTwo, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           leftWheel,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           raise,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           leftWheelTwo,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           liftOne,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           liftTwo,       tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
bool autonSide = true;
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

  //activate LCD
  bDisplayCompetitionStatusOnLcd = true;
  bLCDBacklight = true;
  /*
  int volts =  nImmediateBatteryLevel;
  string voltage = sprintf("", "%d", volts);
  displayLCDCenteredString(0, "LEFT");
  displayLCDCenteredString(1, voltage);
  while(nLCDButtons != 2){ //While center not pressed
    if(nLCDButtons == 0) //No button pressed
      wait1Msec(10); //Do nothing
    else{ //Some button was pressed
      if(nLCDButtons == 1){
        autonSide = true; //Decrement if left press
      }
      else if(nLCDButtons == 4){
        autonSide = false; //Increment if right press
      }
      //Update display
      clearLCDLine(0);
      if(autonSide){
      	displayLCDCenteredString(0, "LEFT");
    	}else{
    		displayLCDCenteredString(0, "RIGHT");
    	}

      while(nLCDButtons != 0){//Wait for release
        wait1Msec(10); //Wait for multitasking.
      }
  	}
  }
  */
}


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous(){
	if(autonSide){
		//pick up
		motor[grabber] = -127;
		delay(200);
		motor[grabber] = 0;
		//lift
		motor[liftOne] = 127;
		motor[liftTwo] = 127;
		delay(1500);
		motor[liftOne] = 0;
		motor[liftTwo] = 0;
		//lower mobile goal raiser
		motor[raise] = -127;
		delay(100);
		motor[raise] = 0;
		//move forward
		motor[rightWheel] = 60;
		motor[leftWheel] = 60;
		motor[rightWheelTwo] = 60;
		motor[leftWheelTwo] = 60;
		delay(3800);
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheelTwo] = 0;
		motor[leftWheelTwo] = 0;
		//drop cone
		motor[grabber] = 127;
		delay(200);
		motor[grabber] = 0;
		//pick mobile goal
		motor[raise] = 127;
		delay(1000);
		motor[raise] = 0;
		//reverse
		motor[rightWheel] = -60;
		motor[leftWheel] = -60;
		motor[rightWheelTwo] = -60;
		motor[leftWheelTwo] = -60;
		delay(2000);
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheelTwo] = 0;
		motor[leftWheelTwo] = 0;
		//turn right 90
		motor[rightWheel] = -60;
		motor[rightWheelTwo] = -60;
		delay(1000);
		motor[rightWheel] = 0;
		motor[rightWheelTwo] = 0;
		//forward a tad
		motor[rightWheel] = 60;
		motor[leftWheel] = 60;
		motor[rightWheelTwo] = 60;
		motor[leftWheelTwo] = 60;
		delay(1000);
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheelTwo] = 0;
		motor[leftWheelTwo] = 0;
		//turn right 90
		motor[rightWheel] = -60;
		motor[rightWheelTwo] = -60;
		delay(1000);
		motor[rightWheel] = 0;
		motor[rightWheelTwo] = 0;
		//forward
		motor[rightWheel] = 60;
		motor[leftWheel] = 60;
		motor[rightWheelTwo] = 60;
		motor[leftWheelTwo] = 60;
		delay(2800);
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheelTwo] = 0;
		motor[leftWheelTwo] = 0;
		//drop
		motor[raise] = -127;
		delay(1000);
		motor[raise] = 0;
		//backup
		motor[rightWheel] = -60;
		motor[leftWheel] = -60;
		motor[rightWheelTwo] = -60;
		motor[leftWheelTwo] = -60;
		delay(1000);
		motor[rightWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheelTwo] = 0;
		motor[leftWheelTwo] = 0;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


//DEADBAND
int deadBand(int val){
	if(fabs(val) <= 10){
		return(0);
	}else{
		return(val);
	}
}

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	//LCD
  /*
	  bDisplayCompetitionStatusOnLcd = true;
	  bLCDBacklight = true;
	  int volts =  nImmediateBatteryLevel;
	  string voltage = sprintf("", "%d", volts);
	  displayLCDCenteredString(0, "LEFT");
	  displayLCDCenteredString(1, voltage);
	  */

		//MOVE with joysticks
		motor[rightWheel] = deadBand(vexRT[Ch2]) - deadBand(vexRT[Ch1]) - deadBand(vexRT[Ch4]);
		motor[rightWheelTwo] = deadBand(vexRT[Ch2]) - deadBand(vexRT[Ch1]) - deadBand(vexRT[Ch4]);
		motor[leftWheel] = deadBand(vexRT[Ch2]) + deadBand(vexRT[Ch1]) + deadBand(vexRT[Ch4]);
		motor[leftWheelTwo] = deadBand(vexRT[Ch2]) + deadBand(vexRT[Ch1]) + deadBand(vexRT[Ch4]);


		//raise and lower lift MOBILE GOAL
		motor[raise] = deadBand(vexRT[Ch3Xmtr2]);
		motor[raise] = deadBand(vexRT[Ch3Xmtr2]);

		//raise and lift X-LIFT in unison
		if(vexRT[Btn7U]==1){
			motor[liftOne] = 127;
			motor[liftTwo] = 127;
		}
		else if(vexRT[Btn7D]==1){
			motor[liftOne] = -127;
			motor[liftTwo] = -127;
		}
		//one side x-lift at a time
		else if(vexRT[Btn8LXmtr2]==1){
			motor[liftOne] = 127;
		}
		else if(vexRT[Btn8RXmtr2]==1){
			motor[liftTwo] = 127;
		}
		//x-lift joy stick
		else{
			motor[liftOne] = deadBand(vexRT[Ch2Xmtr2]);
			motor[liftTwo] = deadBand(vexRT[Ch2Xmtr2]);
	 	}

		//GRAB with x-lift RUBBERS joystick
		motor[grabber] = deadBand(vexRT[Ch4Xmtr2]);
  }
}
